// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDblDmHRr5v0q_Iu4zlD0ijRt7CPdzSSkM',
    appId: '1:78717680757:web:d80a922a7b56ceb6bccc3c',
    messagingSenderId: '78717680757',
    projectId: 'newreader-4cf16',
    authDomain: 'newreader-4cf16.firebaseapp.com',
    storageBucket: 'newreader-4cf16.appspot.com',
    measurementId: 'G-1PE4QF460W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV06VFL8H3VLMssWWxxcXgU-TlnkTkXs0',
    appId: '1:78717680757:android:14b8d9b18e3d9ecebccc3c',
    messagingSenderId: '78717680757',
    projectId: 'newreader-4cf16',
    storageBucket: 'newreader-4cf16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb8RQM4G0kEy3ubnbC6-JMV9h7toWR3ME',
    appId: '1:78717680757:ios:e751b6527759ce29bccc3c',
    messagingSenderId: '78717680757',
    projectId: 'newreader-4cf16',
    storageBucket: 'newreader-4cf16.appspot.com',
    iosClientId: '78717680757-a0j3pmv9kqo4dmdf8k4ns75bfsh0goij.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb8RQM4G0kEy3ubnbC6-JMV9h7toWR3ME',
    appId: '1:78717680757:ios:e751b6527759ce29bccc3c',
    messagingSenderId: '78717680757',
    projectId: 'newreader-4cf16',
    storageBucket: 'newreader-4cf16.appspot.com',
    iosClientId: '78717680757-a0j3pmv9kqo4dmdf8k4ns75bfsh0goij.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsReader',
  );
}
